version: "3.8"

services:
    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./docker/nginx/config:/etc/nginx/conf.d
            - ./docker/nginx/ssl:/etc/ssl/
